name: CI

on:
  issue_comment:
    types: [created, edited, deleted]

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  MSRV: "1.63"

jobs:
  netsim:
    name: Run network simulations/benchmarks
    if: >-
      github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
          github.event.comment.body == '/perf'
    runs-on: [self-hosted, linux, X64]
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive